### ISSUE TITLE
large network

### ISSUE THREAD

**Issue by allan-sanches** [briatte/ggnet#35] opened 2018-11-27 20:55 UTC
When I tried plot a network I receive this error "Removed 509 rows containing missing values (geom_segment). " 
I dont know what the problem is, the lines and collumns colapsed in the same  edges and others lists are created. in same matrices I cannot have this error.
sorry if is my bad, i can't find a solution.
![image](https://user-images.githubusercontent.com/38731217/49110820-a64d9d80-f275-11e8-885d-699e853df9ae.png)

**Comment by briatte** [comment] 2019-06-27 12:33
Dear @allan296 

Thanks for reporting this, and sorry for answering only now.

It's not possible for me to understand what is happening from your screenshot: I'd need a copy of your network object.

Please copy the structure of your object into e.g. [a Gist](https://gist.github.com), and post the link to it:

```r
dput(bip)
```

Closing the issue since it seems like the problem is with the network object and not `ggnet` itself.

**Closed as completed by briatte** 2019-06-27 12:33 UTC
Labels: question, wontfix
